# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: make lint
